// client/src/components/AdminUser.vue
<script setup lang="ts">
import type User from "@/models/User";
import { useStore } from "@/stores/user";
import { useCookies } from "@vueuse/integrations/useCookies";
import { ref } from "vue";
import { useRouter } from "vue-router";
import FormButton from "./FormButton.vue";

const store = useStore();
const router = useRouter();
const cookies = useCookies();

const props = defineProps<{ id: string; update: () => unknown }>();

const info = ref<User>({
  id: props.id,
  username: "",
  email: "",
  balance: 0,
  isStaff: false,
  profit: { daily: 0, total: 0 },
});

fetch(`/api/users/${props.id}`, {
  headers: {
    Authorization: cookies.get("token"),
  },
}).then(async (resp) => {
  const data: {
    type: number;
    name?: string;
    message?: string;
    user?: User;
  } = await resp.json();

  if (data.type !== 0) {
    alert(`Error, ${data.type}, ${data.name}, ${data.message}`);
    cookies.remove("token");
    store.update();
    router.push("login");
  } else {
    info.value = data.user as User;
  }
});

const del = async (e: Event) => {
  e.preventDefault();

  const resp = await fetch(`/api/users/${props.id}`, {
    method: "DELETE",
    headers: {
      Authorization: cookies.get("token"),
    },
  });

  const data: {
    type: number;
    name?: string;
    message?: string;
  } = await resp.json();

  if (data.type !== 0) {
    alert(`Error, ${data.type}, ${data.name}, ${data.message}`);
    cookies.remove("token");
    store.update();
    router.push("login");
  } else {
    alert("Success");
    props.update();
  }
};

const edit = async (e: Event) => {
  e.preventDefault();

  const balance = Number(
    prompt("Enter new balance", info.value.balance.toString())
  );

  if (isNaN(balance)) {
    alert("Invalid input");
    return;
  }

  const daily = Number(
    prompt("Enter new daily profit", info.value.profit.daily.toString())
  );

  if (isNaN(daily)) {
    alert("Invalid input");
    return;
  }

  const total = Number(
    prompt("Enter new total profit", info.value.profit.total.toString())
  );

  if (isNaN(total)) {
    alert("Invalid input");
    return;
  }

  const resp = await fetch(`/api/users/${props.id}`, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      Authorization: cookies.get("token"),
    },
    body: JSON.stringify({ balance, profit: { daily, total } }),
  });

  const data: {
    type: number;
    name?: string;
    message?: string;
  } = await resp.json();

  if (data.type !== 0) {
    alert(`Error, ${data.type}, ${data.name}, ${data.message}`);
    cookies.remove("token");
    store.update();
    router.push("login");
  } else {
    alert("Success");
    props.update();
    info.value.balance = balance;
    info.value.profit = { daily, total };
  }
};
</script>

<template>
  <div class="user">
    <h3>{{ info.username }}</h3>
    <h4>
      ID: <span>{{ info.id }}</span>
    </h4>
    <h4>
      Email: <span>{{ info.email }}</span>
    </h4>
    <h4 class="last">
      <span>${{ info.balance }}</span>
    </h4>
    <div class="options">
      <FormButton @click="del">Delete</FormButton>
      <FormButton @click="edit">Edit</FormButton>
    </div>
  </div>
</template>

<style scoped lang="less">
.user {
  display: flex;
  flex-direction: column;
  padding: 1rem;
  background-color: var(--background-tertiary);
  border: 1px solid rgba(84, 84, 84, 0.65);
  border-radius: 8px;

  h3 {
    margin: 0;
    color: var(--heading);
  }

  h4 {
    margin: 0;
    color: darkgray;
    text-align: right;

    &.last {
      margin-bottom: 1rem;
    }

    span {
      color: var(--heading);
    }
  }
}

.options {
  display: flex;
  flex-direction: row;
  padding: 0;
  margin: 0;
  gap: 0.5rem;
  align-self: center;
}
</style>

// client/src/Components/AdminUser.tsx
import React from 'react';
import styled from 'styled-components';
import Cookies from 'universal-cookie';
import Button from './Button';

const User = styled.div`
  display: flex;
  flex-direction: column;
  padding: 1rem;
  background-color: var(--background-tertiary);
  border: 1px solid rgba(84, 84, 84, 0.65);
  border-radius: 8px;

  h3 {
    margin: 0;
    color: var(--heading);
  }

  h4 {
    margin: 0;
    color: darkgray;
    text-align: right;

    &.last {
      margin-bottom: 1rem;
    }

    span {
      color: var(--heading);
    }
  }
`;

const Options = styled.div`
  display: flex;
  flex-direction: row;
  padding: 0;
  margin: 0;
  gap: 0.5rem;
  align-self: center;
`;

type Props = {
  id: string;
  update: () => Promise<void>;
};

type State = {
  info: {
    id: string;
    username: string;
    email: string;
    balance: number;
  };
};

export default class AdminUser extends React.PureComponent<Props, State> {
  constructor(props: Props | Readonly<Props>) {
    super(props);

    this.state = {
      info: {
        id: '',
        username: '',
        email: '',
        balance: 0,
      },
    };

    this.delete = this.delete.bind(this);
    this.editBalance = this.editBalance.bind(this);
    this.update = this.update.bind(this);
  }

  async update() {
    const token = new Cookies().get('token');

    const resp = await fetch(`/api/users/${this.props.id}`, {
      headers: {
        Authorization: token,
      },
    });
    const data: {
      type: number;
      name?: string;
      message?: string;
      user?: { id: string; username: string; email: string; balance: number };
    } = await resp.json();

    if (data.type === 0) {
      const user = data.user!;
      this.setState({ info: user });
    } else {
      alert(`Error, ${data.type}, ${data.name}, ${data.message}`);
    }
  }

  async componentDidMount() {
    await this.update();
  }

  async delete(e: React.MouseEvent) {
    const token = new Cookies().get('token');

    const resp = await fetch(`/api/users/${this.props.id}`, {
      method: 'DELETE',
      headers: {
        Authorization: token,
      },
    });
    const data: {
      type: number;
      name?: string;
      message?: string;
    } = await resp.json();

    if (data.type === 0) this.props.update();
    else alert(`Error, ${data.type}, ${data.name}, ${data.message}`);
  }

  async editBalance(e: React.MouseEvent) {
    const token = new Cookies().get('token');

    const balance = Number(
      prompt('Enter new balance', this.state.info.balance.toString()),
    );

    if (isNaN(balance)) {
      alert('Invalid input');
      return;
    }

    const resp = await fetch(`/api/users/${this.props.id}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: token,
      },
      body: JSON.stringify({ balance: balance }),
    });
    const data: {
      type: number;
      name?: string;
      message?: string;
    } = await resp.json();

    if (data.type === 0) {
      await this.update();
      await this.props.update();
    } else alert(`Error, ${data.type}, ${data.name}, ${data.message}`);
  }

  render() {
    return (
      <User>
        <h3>{this.state.info.username}</h3>
        <h4>
          ID: <span>{this.state.info.id}</span>
        </h4>
        <h4>
          Email: <span>{this.state.info.email}</span>
        </h4>
        <h4 className="last">
          <span>{this.state.info.balance}$</span>
        </h4>
        <Options>
          <Button onClick={this.delete}>Delete</Button>
          <Button onClick={this.editBalance}>Edit Balance</Button>
        </Options>
      </User>
    );
  }
}
